name: flutter_editor_html
description: Text Editor in Flutter for Android and iOS to help free write
  WYSIWYG HTML code based on Summernote 0.8.18 javascript wrapper.
version: 1.1.1
homepage: https://summernote.org
repository: https://github.com/chandrabezzo/flutter_editor_html
documentation: https://summernote.org
issue_tracker: https://github.com/chandrabezzo/flutter_editor_html/issues

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  image_picker: ^1.0.7
  path: ^1.8.2
  mime: ^1.0.4
  cross_file: ^0.3.3+4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# Next, run the publish command in dry-run mode to see if everything passes analysis:
# flutter pub publish --dry-run
# The next step is publishing to pub.dev, but be sure that you are ready because publishing is forever:
# flutter pub publish
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
